<?php

namespace AppBundle\Repository;

/**
 * AssigneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssigneeRepository extends \Doctrine\ORM\EntityRepository
{
}
